name: stroke_mlflow_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn
      - xgboost
      - imbalanced-learn
      - matplotlib
      - python-dotenv
